---
config:
  layout: elk
  look: classic
---
stateDiagram-v2
    state "Rašytojų poreikių analizė" as req_analysis
    state "Technologinių sprendimų analizė" as tech_analysis
    state "Įrankių projektavimas" as tool_design
    state "Įrankių įgyvendinimas" as tech_choice
    state "Įrankių testavimas" as testing
    state "Diegimo infrastruktūros ruošimas" as infra
    state "Įrankių ruošimas diegimui" as install
    state "Dokumentacijos ruošimas" as docs

    [*] --> req_analysis
    req_analysis --> tech_analysis
    tech_analysis --> tool_design
    tool_design --> tech_choice
    tech_choice --> testing
    testing --> infra
    infra --> docs
    docs --> install
    install --> [*]